FROM golang:1.21-bookworm as builder

ARG GITCOMMIT=docker
ARG GITDATE=docker
ARG GITVERSION=docker

RUN apt update && apt install -y git

COPY ./proxyd /app

WORKDIR /app

RUN make proxyd

FROM debian:bookworm-slim

EXPOSE 8080

VOLUME /etc/proxyd

COPY --from=builder /app/bin/proxyd /bin/proxyd

ENTRYPOINT ["/bin/proxyd"]
CMD ["/etc/proxyd/proxyd.toml"]
