inputs:
  github_token:
    required: true

outputs:
  ref:
    value: ${{ steps.gitref.outputs.ref }}

runs:
  using: composite
  steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    - name: Output ref
      id: gitref
      run: echo "ref=$(echo ${{ github.ref_name }} | cut -d/ -f2)" >> $GITHUB_OUTPUT
      shell: bash
