inputs:
  github-token:
    required: true
  checkout-repo:
    required: true
  checkout-ssh-key:
    default: ''

outputs:
  ref:
    value: ${{ steps.gitref.outputs.out0 }}
  commit-hash:
    value: ${{ steps.commithash.outputs.out0 }}

runs:
  using: composite
  steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Output ref
      id: gitref
      run: echo "out0=$(echo ${{ github.ref_name }} | cut -d/ -f2)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.checkout-repo }}
        ssh-key: ${{ inputs.checkout-ssh-key }}
        ref: ${{ steps.gitref.outputs.out0 }}

    - name: Output commit-hash
      id: commithash
      run: echo "out0=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
      shell: bash
