name: Build

on:
  push:
    tags:
      - 'optimism/*'

env:
  REPOSITORY: akgames-sn

jobs:
  optimism:
    if: startsWith(github.ref_name, 'optimism/')
    name: Build optimism
    runs-on: ubuntu-latest
    steps:
      - name: Get REF
        run: echo "REF=$(echo ${{ github.ref_name }} | cut -d/ -f2)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ethereum-optimism/optimism
          ref: ${{ env.REF }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/bake-action@v4
        env:
          REGISTRY: ghcr.io
          REPOSITORY: ${{ env.REPOSITORY }}/optimism
          GIT_COMMIT: ${{ github.sha }}
          GIT_VERSION: ${{ github.ref_name }}
          GIT_BUILDNUM: ${{ github.run_id }}
          IMAGE_TAGS: ${{ env.REF }}
        with:
          files: docker-bake.hcl
          targets: op-node,op-batcher,op-proposer
          set: '*.platform=linux/amd64'
          # set: '*.platform=linux/amd64,linux/arm64'
          push: true
