name: Build

on:
  push:
    tags:
      - 'optimism/v*'

jobs:
  optimism:
    if: startsWith(github.ref_name, 'optimism/v')
    name: Build optimism
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.actor }}/optimism
          path: optimism
          token: ${{ secrets.token }}

      - name: ls
        run: ls -la optimism

    #   - name: Setup QEMU
    #     uses: docker/setup-qemu-action@v3

    #   - name: Setup Docker Buildx
    #     uses: docker/setup-buildx-action@v3

    #   - name: Login to GitHub Container Registry
    #     uses: docker/login-action@v3
    #     with:
    #       registry: ghcr.io
    #       username: ${{ github.actor }}
    #       password: ${{ secrets.GITHUB_TOKEN }}

    #   - name: Build and Push
    #     uses: docker/bake-action@v4
    #     env:
    #       REGISTRY: ghcr.io
    #       REPOSITORY: ${{ github.repository }}
    #       GIT_COMMIT: ${{ github.sha }}
    #       GIT_VERSION: ${{ github.ref_name }}
    #       GIT_BUILDNUM: ${{ github.run_id }}
    #       IMAGE_TAGS: ${{ github.ref_name }}
    #     with:
    #       files: docker-bake.hcl
    #       set: '*.platform=linux/amd64,linux/arm64'
    #       push: true
