name: Build

permissions:
  packages: write

on:
  push:
    tags:
      - 'optimism/*'
      - 'op-geth/*'
      - 'op-proxyd/*'

env:
  IMAGE_REPO: akgames-sn/build-hub
  OPTIMISM_REPO: AKGAMES-SN/optimism
  OPGETH_REPO: AKGAMES-SN/op-geth
  OPPROXYD_REPO: ethereum-optimism/infra

jobs:
  optimism:
    if: startsWith(github.ref_name, 'optimism/')
    name: optimism
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        id: setup
        uses: ./.github/workflows/setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          checkout-repo: ${{ env.OPTIMISM_REPO }}
          checkout-ssh-key: ${{ secrets.OPTIMISM_REPO_SSH_KEY }}
          checkout-path: app

      - name: Build and Push
        uses: docker/bake-action@v4
        env:
          REGISTRY: ghcr.io
          REPOSITORY: ${{ env.IMAGE_REPO }}
          GIT_COMMIT: ${{ steps.setup.outputs.commit-hash }}
          GIT_VERSION: ${{ steps.setup.outputs.ref }}
          IMAGE_TAGS: ${{ steps.setup.outputs.ref }}
        with:
          workdir: app
          files: docker-bake.hcl
          targets: op-node,op-batcher,op-proposer
          set: '*.platform=linux/amd64,linux/arm64'
          push: true

  op-geth:
    if: startsWith(github.ref_name, 'op-geth/')
    name: op-geth
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        id: setup
        uses: ./.github/workflows/setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          checkout-repo: ${{ env.OPGETH_REPO }}
          checkout-ssh-key: ${{ secrets.OPGETH_REPO_SSH_KEY }}
          checkout-path: app

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: app
          file: ./Dockerfile
          tags: ghcr.io/${{ env.IMAGE_REPO }}/op-geth:${{ steps.setup.outputs.ref }}
          build-args: |
            COMMIT=${{ steps.setup.outputs.commit-hash }}
            VERSION=${{ steps.setup.outputs.ref }}
            BUILDNUM=${{ github.run_id }}
          platforms: linux/amd64,linux/arm64
          push: true

  op-proxyd:
    if: startsWith(github.ref_name, 'op-proxyd/')
    name: op-proxyd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        id: setup
        uses: ./.github/workflows/setup
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          checkout-repo: ${{ env.OP_PROXYD_REPO }}
          checkout-path: app

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: app
          file: ./proxyd/Dockerfile
          tags: ghcr.io/${{ env.IMAGE_REPO }}/op-proxyd:${{ steps.setup.outputs.ref }}
          build-args: |
            GITCOMMIT=${{ steps.setup.outputs.commit-hash }}
            GITVERSION=${{ steps.setup.outputs.ref }}
          platforms: linux/amd64,linux/arm64
          push: true
