name: Build

permissions:
  packages: write

on:
  push:
    tags:
      - 'optimism/*'
      - 'op-geth/*'

env:
  IMAGE_REPO: akgames-sn/build-hub
  OPTIMISM_REPO: AKGAMES-SN/optimism
  OPGETH_REPO: AKGAMES-SN/op-geth

jobs:
  optimism:
    if: startsWith(github.ref_name, 'optimism/')
    name: Build optimism
    runs-on: ubuntu-latest
    steps:
      - name: Set GIT_REF env
        run: echo "GIT_REF=$(echo ${{ github.ref_name }} | cut -d/ -f2)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ env.OPTIMISM_REPO }}
          ref: ${{ env.GIT_REF }}
          ssh-key: ${{ secrets.OPTIMISM_REPO_SSH_KEY }}

      - name: Get GIT_COMMIT
        run: echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Setup docker
        uses: ./.github/workflows/setup-docker

      - name: Build and Push
        uses: docker/bake-action@v4
        env:
          REGISTRY: ghcr.io
          REPOSITORY: ${{ env.IMAGE_REPO }}
          GIT_COMMIT: ${{ env.GIT_COMMIT }}
          GIT_VERSION: ${{ env.GIT_REF }}
          IMAGE_TAGS: ${{ env.GIT_REF }}
        with:
          files: docker-bake.hcl
          targets: op-node,op-batcher,op-proposer
          set: '*.platform=linux/amd64,linux/arm64'
          push: true

  op-geth:
    if: startsWith(github.ref_name, 'op-geth/')
    name: Build op-geth
    runs-on: ubuntu-latest
    steps:
      - name: Set GIT_REF env
        run: echo "GIT_REF=$(echo ${{ github.ref_name }} | cut -d/ -f2)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ env.OPGETH_REPO }}
          ref: ${{ env.GIT_REF }}
          ssh-key: ${{ secrets.OPGETH_REPO_SSH_KEY }}

      - name: Get GIT_COMMIT
        run: echo "GIT_COMMIT=$(git rev-parse HEAD)" >> $GITHUB_ENV

      - name: Setup docker
        uses: ./.github/workflows/setup-docker

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ env.IMAGE_REPO }}/op-geth:${{ env.GIT_REF }}
          build-args: |
            COMMIT=${{ env.GIT_COMMIT }}
            VERSION=${{ env.GIT_REF }}
            BUILDNUM=${{ github.run_id }}
          platforms: linux/amd64,linux/arm64
          push: true
